// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo3vgvR14qo-JpeHt1tPdW8KlfYHqFWvI',
    appId: '1:303850914010:web:b9f58193f816aa8508a5e3',
    messagingSenderId: '303850914010',
    projectId: 'new-chat-app-a6f61',
    authDomain: 'new-chat-app-a6f61.firebaseapp.com',
    storageBucket: 'new-chat-app-a6f61.firebasestorage.app',
    measurementId: 'G-C2EJBG1EB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqAiRgYHNI1_REIesAPg_-2uWmLtjXbs',
    appId: '1:303850914010:android:be56c70007c907b308a5e3',
    messagingSenderId: '303850914010',
    projectId: 'new-chat-app-a6f61',
    storageBucket: 'new-chat-app-a6f61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfb4ncqUUjD_1bfPav2m6KEHSffE0VT3I',
    appId: '1:303850914010:ios:cb4b7e72a5ea25db08a5e3',
    messagingSenderId: '303850914010',
    projectId: 'new-chat-app-a6f61',
    storageBucket: 'new-chat-app-a6f61.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfb4ncqUUjD_1bfPav2m6KEHSffE0VT3I',
    appId: '1:303850914010:ios:cb4b7e72a5ea25db08a5e3',
    messagingSenderId: '303850914010',
    projectId: 'new-chat-app-a6f61',
    storageBucket: 'new-chat-app-a6f61.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo3vgvR14qo-JpeHt1tPdW8KlfYHqFWvI',
    appId: '1:303850914010:web:995a62cfd5d47ce708a5e3',
    messagingSenderId: '303850914010',
    projectId: 'new-chat-app-a6f61',
    authDomain: 'new-chat-app-a6f61.firebaseapp.com',
    storageBucket: 'new-chat-app-a6f61.firebasestorage.app',
    measurementId: 'G-DSMYFS7BWZ',
  );
}
